component_depth: 1
languages:
- java
exclude:
- ./META-INF/.*
- ./classesEclipse/.*
- ./classesEclipse/docbook/.*
- ./classesEclipse/docbook/ent/.*
- ./classesEclipse/edu/.*
- ./classesEclipse/edu/umd/.*
- ./classesEclipse/edu/umd/cs/.*
- ./classesEclipse/edu/umd/cs/findbugs/.*
- ./classesEclipse/edu/umd/cs/findbugs/annotations/.*
- ./classesEclipse/edu/umd/cs/findbugs/anttask/.*
- ./classesEclipse/edu/umd/cs/findbugs/architecture/.*
- ./classesEclipse/edu/umd/cs/findbugs/asm/.*
- ./classesEclipse/edu/umd/cs/findbugs/ba/.*
- ./classesEclipse/edu/umd/cs/findbugs/ba/bcp/.*
- ./classesEclipse/edu/umd/cs/findbugs/ba/ca/.*
- ./classesEclipse/edu/umd/cs/findbugs/ba/ch/.*
- ./classesEclipse/edu/umd/cs/findbugs/ba/constant/.*
- ./classesEclipse/edu/umd/cs/findbugs/ba/deref/.*
- ./classesEclipse/edu/umd/cs/findbugs/ba/generic/.*
- ./classesEclipse/edu/umd/cs/findbugs/ba/heap/.*
- ./classesEclipse/edu/umd/cs/findbugs/ba/interproc/.*
- ./classesEclipse/edu/umd/cs/findbugs/ba/jsr305/.*
- ./classesEclipse/edu/umd/cs/findbugs/ba/npe/.*
- ./classesEclipse/edu/umd/cs/findbugs/ba/npe2/.*
- ./classesEclipse/edu/umd/cs/findbugs/ba/obl/.*
- ./classesEclipse/edu/umd/cs/findbugs/ba/rta/.*
- ./classesEclipse/edu/umd/cs/findbugs/ba/type/.*
- ./classesEclipse/edu/umd/cs/findbugs/ba/vna/.*
- ./classesEclipse/edu/umd/cs/findbugs/bcel/.*
- ./classesEclipse/edu/umd/cs/findbugs/classfile/.*
- ./classesEclipse/edu/umd/cs/findbugs/classfile/analysis/.*
- ./classesEclipse/edu/umd/cs/findbugs/classfile/engine/.*
- ./classesEclipse/edu/umd/cs/findbugs/classfile/engine/asm/.*
- ./classesEclipse/edu/umd/cs/findbugs/classfile/engine/bcel/.*
- ./classesEclipse/edu/umd/cs/findbugs/classfile/impl/.*
- ./classesEclipse/edu/umd/cs/findbugs/cloud/.*
- ./classesEclipse/edu/umd/cs/findbugs/cloud/db/.*
- ./classesEclipse/edu/umd/cs/findbugs/config/.*
- ./classesEclipse/edu/umd/cs/findbugs/detect/.*
- ./classesEclipse/edu/umd/cs/findbugs/filter/.*
- ./classesEclipse/edu/umd/cs/findbugs/graph/.*
- ./classesEclipse/edu/umd/cs/findbugs/gui/.*
- ./classesEclipse/edu/umd/cs/findbugs/gui/bundle/.*
- ./classesEclipse/edu/umd/cs/findbugs/gui/help/.*
- ./classesEclipse/edu/umd/cs/findbugs/gui2/.*
- ./classesEclipse/edu/umd/cs/findbugs/gui2/help/.*
- ./classesEclipse/edu/umd/cs/findbugs/internalAnnotations/.*
- ./classesEclipse/edu/umd/cs/findbugs/io/.*
- ./classesEclipse/edu/umd/cs/findbugs/jaif/.*
- ./classesEclipse/edu/umd/cs/findbugs/log/.*
- ./classesEclipse/edu/umd/cs/findbugs/ml/.*
- ./classesEclipse/edu/umd/cs/findbugs/model/.*
- ./classesEclipse/edu/umd/cs/findbugs/plan/.*
- ./classesEclipse/edu/umd/cs/findbugs/props/.*
- ./classesEclipse/edu/umd/cs/findbugs/tools/.*
- ./classesEclipse/edu/umd/cs/findbugs/tools/html/.*
- ./classesEclipse/edu/umd/cs/findbugs/tools/junit/.*
- ./classesEclipse/edu/umd/cs/findbugs/tools/xml/.*
- ./classesEclipse/edu/umd/cs/findbugs/util/.*
- ./classesEclipse/edu/umd/cs/findbugs/visitclass/.*
- ./classesEclipse/edu/umd/cs/findbugs/workflow/.*
- ./classesEclipse/edu/umd/cs/findbugs/xml/.*
- ./classesEclipse/net/.*
- ./classesEclipse/net/jcip/.*
- ./classesEclipse/net/jcip/annotations/.*
- ./design/.*
- ./design/architecture/.*
- ./doc/.*
- ./doc/customers/.*
- ./doc/ja/.*
- ./doc/ja/manual/.*
- ./doc/manual/.*
- ./etc/.*
- ./etc/docbook/.*
- ./etc/docbook/ent/.*
- ./jnlp/.*
- ./lib/.*
- ./nbproject/.*
- ./plugin/.*
